# Generated by Django 5.0.14 on 2026-06-07 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar en lugar de borrar (soft-delete).', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('guest_name', models.CharField(blank=True, default='', help_text='Nombre del jugador invitado (cuando user es null, ADR-008).', max_length=120, verbose_name='Nombre del invitado')),
                ('guest_phone', models.CharField(blank=True, default='', help_text='Teléfono de contacto del invitado (cuando user es null, ADR-008).', max_length=30, verbose_name='Teléfono del invitado')),
                ('start_dt', models.DateTimeField(help_text='Fecha y hora de inicio del turno, siempre en UTC.', verbose_name='Inicio del turno (UTC)')),
                ('end_dt', models.DateTimeField(help_text='Fecha y hora de fin. end_dt = start_dt + court.slot_duration_minutes (ADR-006).', verbose_name='Fin del turno (UTC)')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada')], default='PENDING_PAYMENT', help_text='Estado de la reserva según el workflow definido en WORKFLOW.md.', max_length=20, verbose_name='Estado')),
                ('price', models.DecimalField(decimal_places=2, help_text='Snapshot del precio de la cancha al momento de crear la reserva.', max_digits=10, verbose_name='Precio')),
                ('cancellation_reason', models.CharField(blank=True, default='', help_text='Motivo de cancelación. Obligatorio si el estado es CANCELLED.', max_length=255, verbose_name='Motivo de cancelación')),
                ('court', models.ForeignKey(help_text='Cancha reservada.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='courts.court', verbose_name='Cancha')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario registrado que reserva. Null si es reserva de invitado (ADR-008).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-start_dt'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del movimiento en pesos. Corresponde al precio de la reserva.', max_digits=10, verbose_name='Monto')),
                ('notes', models.CharField(blank=True, default='', help_text='Notas adicionales (ej: referencia de transferencia, motivo de cancelación).', max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de creación en UTC. Inmutable.', verbose_name='Creado en')),
                ('booking', models.ForeignKey(help_text='Reserva a la que corresponde este movimiento de caja.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='bookings.booking', verbose_name='Reserva')),
                ('operator', models.ForeignKey(help_text='Usuario (operator o admin) que registró el movimiento.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['court', 'status', 'start_dt', 'end_dt'], name='booking_overlap_idx'),
        ),
    ]
