# Generated by Django 5.0.14 on 2026-06-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, default='', help_text='Email de contacto del invitado para notificaciones (cuando user es null, ADR-008).', max_length=254, verbose_name='Email del invitado'),
        ),
    ]
