# Generated by Django 5.0.14 on 2026-06-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_add_guest_email_to_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar en lugar de borrar (soft-delete).', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('phone', models.CharField(help_text="Número del jugador en formato WhatsApp, ej: '5491112345678@c.us'.", max_length=50, verbose_name='Teléfono WhatsApp')),
                ('player_name', models.CharField(blank=True, default='', help_text='Nombre que el jugador proporcionó durante la conversación.', max_length=120, verbose_name='Nombre del jugador')),
                ('direction', models.CharField(choices=[('inbound', 'Entrante (jugador → bot)'), ('outbound', 'Saliente (bot → jugador)')], help_text="'inbound' = mensaje del jugador al bot; 'outbound' = respuesta del bot.", max_length=10, verbose_name='Dirección')),
                ('message', models.TextField(help_text='Texto completo del mensaje.', verbose_name='Mensaje')),
                ('booking', models.ForeignKey(blank=True, help_text='Reserva creada o referenciada durante esta conversación (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_logs', to='bookings.booking', verbose_name='Reserva relacionada')),
            ],
            options={
                'verbose_name': 'Registro de conversación bot',
                'verbose_name_plural': 'Registros de conversación bot',
                'ordering': ['-created_at'],
            },
        ),
    ]
