# Generated by Django 5.0.14 on 2026-06-07 06:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar en lugar de borrar (soft-delete).', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(help_text='Identificador único de la cancha dentro del complejo.', max_length=100, unique=True, verbose_name='Nombre')),
                ('court_type', models.CharField(choices=[('futbol_5', 'Fútbol 5'), ('futbol_7', 'Fútbol 7'), ('padel', 'Pádel')], help_text='Categoría deportiva: fútbol 5, fútbol 7 o pádel.', max_length=20, verbose_name='Tipo de cancha')),
                ('surface', models.CharField(blank=True, help_text='Tipo de superficie (ej: césped sintético, cemento, moqueta).', max_length=50, verbose_name='Superficie')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Precio del turno en pesos. Debe ser mayor o igual a 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio base')),
                ('slot_duration_minutes', models.PositiveIntegerField(help_text='Duración en minutos de cada turno reservable. Determina end_dt = start_dt + slot_duration_minutes (ADR-006).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración del turno (minutos)')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar en lugar de borrar (soft-delete).', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día al que aplica este bloque (0=lunes … 6=domingo, igual que Python date.weekday()).', verbose_name='Día de la semana')),
                ('open_time', models.TimeField(help_text='Hora de inicio de disponibilidad de la cancha.', verbose_name='Hora de apertura')),
                ('close_time', models.TimeField(help_text='Hora de fin de disponibilidad de la cancha. Debe ser mayor que open_time.', verbose_name='Hora de cierre')),
                ('court', models.ForeignKey(help_text='Cancha a la que pertenece este bloque horario.', on_delete=django.db.models.deletion.PROTECT, related_name='schedule_blocks', to='courts.court', verbose_name='Cancha')),
            ],
            options={
                'verbose_name': 'Bloque de horario',
                'verbose_name_plural': 'Bloques de horario',
                'ordering': ['court', 'weekday', 'open_time'],
            },
        ),
    ]
