# Generated by Django 5.0.14 on 2026-06-10 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar en lugar de borrar (soft-delete).', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('start_dt', models.DateTimeField(help_text='Fecha y hora de inicio del bloqueo en UTC.', verbose_name='Inicio del bloqueo (UTC)')),
                ('end_dt', models.DateTimeField(help_text='Fecha y hora de fin del bloqueo en UTC.', verbose_name='Fin del bloqueo (UTC)')),
                ('reason', models.CharField(blank=True, default='', help_text='Motivo del bloqueo (ej: torneo, mantenimiento, cierre anticipado).', max_length=200, verbose_name='Motivo')),
                ('court', models.ForeignKey(help_text='Cancha cuyo horario se bloquea.', on_delete=django.db.models.deletion.CASCADE, related_name='slot_blocks', to='courts.court', verbose_name='Cancha')),
                ('created_by', models.ForeignKey(blank=True, help_text='Operador o admin que creó el bloqueo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slot_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Bloqueo de slot',
                'verbose_name_plural': 'Bloqueos de slots',
                'ordering': ['start_dt'],
            },
        ),
    ]
