# Generated by Django 5.0.14 on 2026-06-10 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar en lugar de borrar (soft-delete).', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('session_date', models.DateField(help_text='Día de la sesión de caja, en hora Buenos Aires (America/Argentina/Buenos_Aires). Solo una sesión por día por tenant.', verbose_name='Fecha de caja')),
                ('opened_at', models.DateTimeField(help_text='Timestamp UTC de apertura de la sesión.', verbose_name='Abierta en (UTC)')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp UTC de cierre. Null mientras la sesión esté abierta.', null=True, verbose_name='Cerrada en (UTC)')),
                ('opening_amount', models.DecimalField(decimal_places=2, help_text='Efectivo declarado en caja al momento de la apertura.', max_digits=10, verbose_name='Monto inicial')),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo físico contado por el cajero al cerrar la sesión.', max_digits=10, null=True, verbose_name='Monto contado al cierre')),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado al cerrar: opening_amount + suma de CashMovement.amount del día. Sirve como referencia para detectar diferencias.', max_digits=10, null=True, verbose_name='Monto esperado')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, help_text='closing_amount - expected_amount. Negativo = faltante; positivo = sobrante.', max_digits=10, null=True, verbose_name='Diferencia')),
                ('notes', models.TextField(blank=True, default='', help_text='Notas del cajero al cerrar la sesión (diferencias, incidentes, etc.).', verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', help_text='OPEN: sesión abierta. CLOSED: sesión cerrada.', max_length=10, verbose_name='Estado')),
                ('operator', models.ForeignKey(help_text='Usuario (operator o tenant_admin) que abrió la sesión de caja.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Sesión de caja',
                'verbose_name_plural': 'Sesiones de caja',
                'ordering': ['-session_date'],
                'unique_together': {('session_date',)},
            },
        ),
    ]
