# Generated by Django 5.0.14 on 2026-06-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar en lugar de borrar (soft-delete).', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('complex_name', models.CharField(help_text='Nombre que verá el jugador en la grilla y en las notificaciones.', max_length=200, verbose_name='Nombre público del complejo')),
                ('payment_instructions', models.TextField(blank=True, default='', help_text="Texto libre con indicaciones para que el jugador pague la seña (ej: 'Transferí al CBU indicado y enviá el comprobante por WhatsApp').", verbose_name='Instrucciones de pago')),
                ('cbu_alias', models.CharField(blank=True, default='', help_text='Alias de la cuenta bancaria o billetera virtual del complejo.', max_length=100, verbose_name='Alias CBU/CVU')),
                ('cbu_number', models.CharField(blank=True, default='', help_text='CBU o CVU de 22 dígitos para transferencias bancarias.', max_length=22, verbose_name='Número de CBU/CVU')),
                ('account_holder', models.CharField(blank=True, default='', help_text='Nombre del titular de la cuenta bancaria o billetera.', max_length=200, verbose_name='Titular de la cuenta')),
                ('phone', models.CharField(blank=True, default='', help_text='Número de teléfono del complejo (ej: +5491112345678).', max_length=30, verbose_name='Teléfono de contacto')),
                ('instagram', models.CharField(blank=True, default='', help_text="Usuario de Instagram sin el @. Ej: 'complejolospinos'.", max_length=100, verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, default='', help_text='Número de WhatsApp en formato internacional (ej: +5491112345678).', max_length=30, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Configuración del complejo',
                'verbose_name_plural': 'Configuraciones del complejo',
            },
        ),
    ]
