# Generated by Django 5.0.14 on 2026-06-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_platformadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='bot_mode',
            field=models.CharField(choices=[('mock', 'Demo (conversaciones seed)'), ('production', 'Producción (mensajes reales)')], default='production', help_text='mock: muestra conversaciones seed de demostración. production: muestra mensajes reales del bot WhatsApp.', max_length=20, verbose_name='Modo del bot'),
        ),
    ]
